version: '3'
services:
  elasticsearch:
    image: elasticsearch:latest
  kibana:
    image: kibana:latest
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
  logstash:
    image: logstash:latest
    command: -e 'input { tcp { port => 5555 }} output { elasticsearch { => ["elasticsearch:92000"] } }'
    ports:
      - "5555:5555"
    depends_on:
      - elasticsearch
       