version: '3'
services:
  testapp:
    image: andrewnascimento/personal:testapp-v1
    deploy:
      com.testapp.description: "This is a test app"
      replicas: 2   # how many containers
      restart_policy: 
        condition: on-failure # condition to restart
      resources:
        limits:
          cpus: "0.2"    # how much cpu
          memory: 50M    # how much ram
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/code
      - logvolume01:/var/log
    networks:
     - testapp_net    # network name
volumes:
  logvolume01: {}
networks:
  testapp_net:
dns:
  - <server 1>
  - <server 2>
dns_search:
  - example.com
  - example2.com
